### ISSUE TITLE
Cant KEEP me out your mouth.

### ISSUE THREAD

**Issue by dreamingrainbow** [AndrewVanardennen/Purr#7]
https://rarible.com/token/polygon/0x35f8aee672cde8e5fd09c93d2bfe4ff5a9cf0756:112954410210801360540676792813908180493511188877071264152194072809828958339074

**Comment by VandeurenGlenn** [comment]
@dreamingrainbow So you posted some really "art" of an nft that you made 17 days ago? Because others probably are also calling you out for a scammer or atleast looking like one, on a repo of a project I made for my cousin? Gonna be honest, I'm really confused why 🤣 So many other options.

**Comment by VandeurenGlenn** [comment]
Closing this because the opener is living in another reality.
